name: CI Build

on:
  push:
    branches:
      - 'feature/**'
jobs:
  build:
    name: Maven Build
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
#      - name: Set up JDK 21
#        uses: actions/setup-java@v3
#        with:
#          java-version: '21'
#          distribution: 'liberica'
#          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#          settings-path: ${{ github.workspace }} # location for the settings.xml file
#
#      - name: Build with Maven
#        run: ./mvnw -B verify --file pom.xml

      - name: Set up Graal
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native image using Graal
        run: ./mvnw -B -DskipTests -ntp --file pom.xml -Pnative native:compile

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            target/**/*.*
