name: CI Build

on:
  push:
    branches:
      - 'feature/**'
jobs:
  build:
    name: 'Maven Build on ${{ matrix.os }}'
    strategy:
      fail-fast: true
      matrix:
        os: [ macOS-latest, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Graal
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native image using Graal
        run: ./mvnw -B -ntp --file pom.xml -Pnative native:compile

      - name: Create distribution
        run: ./mvnw -B -ntp --file pom.xml -Pdist package -DskipTests


      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            target/distributions/*.*
